# Server
server.port=8080

# SQL Server - SQL Login
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=IMGEMR;trustServerCertificate=true;encrypt=false;sendStringParametersAsUnicode=true
spring.datasource.username=bit
spring.datasource.password=bitbit
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# File Storage
emr.image.base-path=F:/A.Work/My Project/EMR Project/EMRIMAGE

# Thymeleaf
spring.thymeleaf.cache=false

# Max file upload size
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# Logging
logging.level.com.emr=DEBUG
